name: sge
services:

    sge_web:
        build: .
        env_file:
            - .env
        environment:
            DB_ENV: prd
            ACTIVE_DB: postgresql
            POSTGRES_DB: ${POSTGRES_DB:-sge}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_HOST: sge_db
            POSTGRES_PORT: 5432
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - sge_db

    sge_db:
        image: postgres:17
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-sge}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
