# Generated by Django 5.0.14 on 2026-01-08 19:34

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_user_created_alter_brand_user_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
